### ISSUE TITLE
xception-c0a72b38.pth.tar

### ISSUE THREAD

**Issue by Janezzliu** [tstandley/Xception-PyTorch#4]
hello, i can't get 'https://www.dropbox.com/s/1hplpzet9d7dv29/xception-c0a72b38.pth.tar?dl=1'.could you please give me your zip link?

**Comment by tstandley** [comment]
Sorry I didn't respond! The weights are mirrored in the [https://github.com/Cadene/pretrained-models.pytorch](url) version
