### ISSUE TITLE
have u compared your speed for dws with normal conv2d?

### ISSUE THREAD

**Issue by wangzheallen** [tstandley/Xception-PyTorch#5]

**Comment by tstandley** [comment]
I'm sorry. I don't even know what this means.

**Comment by wangzheallen** [comment]
sorry for making it confusing. 
When you run the exp for Xception. 
Have you tried to compare the time for running 1 epoch between using
1. depth-wise separable convolution
and using
2. using traditional convolution 

thanks!

**Comment by tstandley** [comment]
The architecture isn't mine, just the pytorch implementation.
To answer your question though, the running time of depth-wise separable convolution is faster than that of traditional convolution. Details are very dependent on hardware and pytorch/cuda/cudnn version. If you want to know how it's going to perform with your setup, you can simply replace the separable convolution code with that of a traditional convolution and run both models.

**Comment by wangzheallen** [comment]
Thanks for the answer, based on my experiment it seems not performing as fast as traditional convolutional, maybe because there is not optimized pytorch/cuda implementation yet. 
Below is the DWS i used.

https://github.com/tstandley/Xception-PyTorch/blob/master/xception.py#L33

**Comment by tstandley** [comment]
What is your pytorch/cuda/cudnn version and what is your hardware situation? FP32 or FP16?
