### ISSUE TITLE
Is the definition of SeparableConv2d wrong ?

### ISSUE THREAD

**Issue by sh1neon** [tstandley/Xception-PyTorch#6]
hi~, I find that the forward function of SeparableConv2d class is different from Xception paper definition. 
In Xception, the order of separable convolution operation should be 1x1 convolution first(pointwise convolution) and then depthwise convolution. 
what do you think?

**Comment by tstandley** [comment]
See the last few paragraphs on the second page of their current arxiv paper. Inception does pointwise first. Xception does channelwise first.

This code was designed to use the same weights and architecture of the keras version exactly.
