### ISSUE TITLE
Model url doesn't work

### ISSUE THREAD

**Issue by langyubo** [tstandley/Xception-PyTorch#8]
The model url "https://www.dropbox.com/s/1hplpzet9d7dv29/xception-c0a72b38.pth.tar?dl=1" doesn't work, would you update a new model weights?

**Comment by tstandley** [comment]
I'd recommend the Cadene repo. They have kept up-to-date. At least for longer. They host the weights themselves. I've copied the link for that to the code here, but I never tried it, so it might not even work. But if you try again it might, or you can just use that repo:

https://github.com/Cadene/pretrained-models.pytorch
